### PR TITLE
Search for file_checksum in the VBF header was broken

### PR DESCRIPTION
**Pull request by esaulenka**
Search for `file_checksum` in the header looks broken, so if you just open and close such file, it can overwrite some blocks data.

This code `header.file_checksum_offset = h.indexOf("0x", offset + 13);` tries to search `0x` _after_ the header, that's completely wrong.
Also, `offset = h.indexOf("}", offset);` is useless, it just returns the same value.

PS looks like it was broken 4 month ago: https://github.com/smartgauges/qvbf/commit/9d33b00144f5cbfc9c80031b655da818e2252b65

### CODE REVIEW

**Comment by smartgauges** [comment]
Thank you for pull request, but i fixed this bug like this: https://github.com/smartgauges/qvbf/commit/1e11a6132614d36ddf16318bd4c2eb7b13ec29a1#diff-d4b374d52015892cf9be9ca1f391cb9413aa7fad2fec933957d7b5623ec5b261L148
What do you think about my bug fix?

**Comment by esaulenka** [comment]
No, it's not working if the `file_checksum` field is not the last in the header.
(and, of course, magic `- 13` is not the best choice ;) )

My sample looks like
```
vbf_version = 3.1;
header
{
....
file_checksum = 0x12345678;

sw_signature = { "long hex string",
"long hex string",
"long hex string"};
}
```

**Comment by smartgauges** [comment]
oops, now I understand what the problem is, I found vbf with similar template

```
vbf_version = 2.4;

header {

    sw_part_number = "FT4T-14G082-ME";

    sw_part_type = EXE;

    network = CAN_HS;

    ecu_address = 0x706;

    frame_format = CAN_STANDARD;

    erase = { { 0x04000000, 0x00ebabdc }
               }; 

    file_checksum=0x8518FFA0;
    data_format_identifier=0x00;
}
```

**Comment by smartgauges** [comment]
Thank you for your help, I fixed the issue here
https://github.com/smartgauges/qvbf/commit/23cd7c5718b0a4c171df43c734f3f1f27f052ebe

**Comment by esaulenka** [comment]
Looks like it works good enough, thanks!

**Pull request closed without merging**
